### PR TITLE
cu_distance_system

### PR DESCRIPTION
**Pull request by icey-ai**
A warmhearted anonymous net friend who wants to make a postive contribution to Common Universalis.
But I'm not good at English, so I may not express my meaning fluently. 
This file is new distance system according to the description in a chat group.(Because current distance system is not flexible and too simplistic.)
At last, thank you for your wonderful mod.
This part is scripted_effects

### CODE REVIEW

**Comment by icey-ai** [comment]
[CUDistance.txt](https://github.com/Corpsemania/Common-Universalis-Internal/files/4540610/CUDistance.txt)
[road_buildings.txt](https://github.com/Corpsemania/Common-Universalis-Internal/files/4540613/road_buildings.txt)
[00_on_actions.txt](https://github.com/Corpsemania/Common-Universalis-Internal/files/4540685/00_on_actions.txt)



Because i dont know how to edit the building ui, the road_0 hasn't a ui temporarily

**Comment by icey-ai** [comment]
[cu_road_modifiers.txt](https://github.com/Corpsemania/Common-Universalis-Internal/files/4540745/cu_road_modifiers.txt)

[localisation.zip](https://github.com/Corpsemania/Common-Universalis-Internal/files/4540756/localisation.zip)

**Comment by icey-ai** [comment]
since i am busy with other works, the numerical simulation may not be good enough.
Your team may need to rewrite so of them after testing the system in EU4

**Comment by icey-ai** [comment]
@Corpsemania can you review my code?

**Comment by Corpsemania** [comment]
> @Corpsemania can you review my code?

private me on qq since you are in the chatting group.

**Comment by icey-ai** [comment]
[02_cu_culture_effects.txt](https://github.com/Corpsemania/Common-Universalis-Internal/files/4544670/02_cu_culture_effects.txt)
[00_on_actions.txt](https://github.com/Corpsemania/Common-Universalis-Internal/files/4544671/00_on_actions.txt)
(fixed a bug(no coodinate set up ) in on_action )

**Pull request merged**
